### ISSUE TITLE
grunt static putting out an error

### ISSUE THREAD

**Issue by justindra** [percolatestudio/percolatestudio.com#48]
Running `grunt static` seems to come up with this error. I'm running this on Windows 10.

``` bash
Running "execute:static" (execute) task
-> executing D:\Projects\trials\trialpercolatea\app\static.js
/
This browser doesn't support the `onScroll` event
Warning: No route matches path "\how\". Make sure you have <Route path="\how\"> somewhere in your routes
\how\
Warning: No route matches path "\what\". Make sure you have <Route path="\what\"> somewhere in your routes
\what\
Warning: No route matches path "\what\:name". Make sure you have <Route path="\what\:name"> somewhere in your routes
\what\:name
D:\Projects\trials\trialpercolatea\node_modules\mkdirp\index.js:92
                if (!stat.isDirectory()) throw err0;
                                         ^

Error: EEXIST: file already exists, mkdir 'D:\Projects\trials\trialpercolatea\static\what'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:794:18)
    at Function.sync (D:\Projects\trials\trialpercolatea\node_modules\mkdirp\index.js:71:13)
    at Object.StaticTools.writeFile (D:\Projects\trials\trialpercolatea\app\lib\StaticTools.jsx:135:12)
    at Object.StaticTools.writeHtmlPage (D:\Projects\trials\trialpercolatea\app\lib\StaticTools.jsx:120:10)
    at Function.<anonymous> (D:\Projects\trials\trialpercolatea\app\static.js:62:17)
    at Function.dispatchHandler (D:\Projects\trials\trialpercolatea\node_modules\react-router\lib\createRouter.js:365:22)
    at D:\Projects\trials\trialpercolatea\node_modules\react-router\lib\createRouter.js:333:29
    at Function.Transition.to (D:\Projects\trials\trialpercolatea\node_modules\react-router\lib\Transition.js:72:15)
    at D:\Projects\trials\trialpercolatea\node_modules\react-router\lib\createRouter.js:332:22
Warning: -> error 1 D:\Projects\trials\trialpercolatea\app\static.js (1178ms) Use --force to continue.

Aborted due to warnings.
```

Not sure what the problem is.

**Comment by justindra** [comment]
So turns out its because windows uses `\` instead of `/` for directories. So have to add these few lines in `app/lib/StaticTools.jsx`.

``` js
interpolate: function(paths, forPath, key, values) {
...
    paths.forEach(function(routePath) {
        routePath = routePath.replace(/\\/g, '/');
...
```

And also mkdir doesn't like filenames being the same name as a directory so had to adjust this also,

``` js
  writeHtmlPage: function(dir, page, contents) {
    // Replace trailing / with index.html
    if (page.match(/\/$/)) {
      page += "index.html";
    } else {
      page += ".html"; // ADDED LINE
    }

    this.writeFile(dir, page, contents);
  },
```
